// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZrWPoYnc2neIHfK_aPgkFwA63HLcmao',
    appId: '1:309006867670:android:6b6fd0d520b71d1a757d77',
    messagingSenderId: '309006867670',
    projectId: 'fir-chat-app-9cbec',
    storageBucket: 'fir-chat-app-9cbec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFn6gq_9KjrNujUi8YEBKY7bP_z0blcVU',
    appId: '1:309006867670:ios:eb517f1057399e54757d77',
    messagingSenderId: '309006867670',
    projectId: 'fir-chat-app-9cbec',
    storageBucket: 'fir-chat-app-9cbec.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLvuMFf5IoSD1xglKl8p30d0InAOCgaZE',
    appId: '1:309006867670:web:101619fe72aa2d78757d77',
    messagingSenderId: '309006867670',
    projectId: 'fir-chat-app-9cbec',
    authDomain: 'fir-chat-app-9cbec.firebaseapp.com',
    storageBucket: 'fir-chat-app-9cbec.firebasestorage.app',
  );

}